spring.application.name=hypertrophy-art
# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/hypertrophy_art
spring.datasource.username=hypertrophy_user
spring.datasource.password=hypertrophy_pass
spring.datasource.driver-class-name=org.postgresql.Driver
# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false
# MongoDB
spring.data.mongodb.uri=mongodb://localhost:27018/hypertrophy_art_mongo
# Swagger
springdoc.swagger-ui.path=/swagger-ui.html